AllCops:
   Include:
     - 'lib/**/*.rb'
     - 'spec/**/*.rb'
   Exclude:
     - 'examples/**/*'
     - 'vendor/**/*'

Metrics/ClassLength:
  Max: 300
  CountComments: false

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 11

Metrics/LineLength:
  Max: 155

Metrics/MethodLength:
  Max: 30

Style/SignalException:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/sentry-raven-without-integrations.rb'
    - 'lib/sentry-raven.rb'

Style/NumericLiterals:
  Exclude:
    - 'spec/raven/processors/sanitizedata_processor_spec.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Lint/RescueException:
  Exclude:
    - 'lib/raven/base.rb'
    - 'lib/raven/instance.rb'
    - 'lib/raven/integrations/delayed_job.rb'
    - 'lib/raven/integrations/rack.rb'
    - 'lib/raven/integrations/sidekiq.rb'
    - 'spec/raven/event_spec.rb'
