Metrics/LineLength:
  Max: 120

Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false